import {cancelExample, speakExample} from './speech.js';
import {version} from '../package.json';
import {compare} from './scoring.js';
import {sentences} from './sentences.js';
const $ = id => document.getElementById(id);
const Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;
let index=0, state='idle', session=null, audioUrl=null;
function status(message){$('status').textContent=message;}
function controls(){const busy=state!=='idle';$('next').disabled=busy;$('listen').disabled=busy||!window.speechSynthesis;$('record').disabled=state==='starting'||state==='stopping'||!Recognition||!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder;$('record').classList.toggle('recording',state==='recording');$('record').innerHTML=state==='recording'?'<span aria-hidden="true">■</span> Finish recording':state==='starting'?'Opening microphone…':state==='stopping'?'Checking your sentence…':'<span aria-hidden="true">●</span> Start recording';}
function render(){const [sentence,translation,verb,tip]=sentences[index];$('sentence').textContent=sentence;$('translation').textContent=translation;$('verb').textContent=verb;$('tip').textContent=tip;$('counter').textContent=`${String(index+1).padStart(2,'0')} / ${sentences.length}`;$('feedback').hidden=true;$('playback').hidden=true;$('audio').removeAttribute('src');if(audioUrl)URL.revokeObjectURL(audioUrl);audioUrl=null;status('Your turn. Tap to record, then tap to finish.');controls();}
function feedback(s){const transcript=s.transcript.trim();if(!transcript){status(s.error||'No words were recognized. Listen to your recording, then try again.');return;}const result=compare(sentences[index][0],transcript);$('feedback').hidden=false;$('result-title').textContent=result.score===100?'¡Excelente!':result.score>=70?'Nice work. Keep going!':'Let’s try that again.';$('score').textContent=`${result.score}% word match`;$('heard').textContent=`Heard: “${transcript}”`;$('words').replaceChildren();sentences[index][0].split(/\s+/).forEach((word,i)=>{const span=document.createElement('span');span.className=`word ${result.matched[i]?'matched':'missed'}`;span.textContent=word;span.title=result.matched[i]?'Recognized':'Try this word again';$('words').append(span);});$('advice').textContent=result.score===100?'All the words matched. Try the next sentence!':'Underlined words need another try. Listen to the example and speak slowly. Extra words also affect the score.';status(s.error||'Recording complete. Your feedback is below.');}
function finish(s){if(session!==s||s.finished||!s.audioDone||!s.speechDone)return;s.finished=true;clearTimeout(s.fallback);clearInterval(s.ticker);s.stream?.getTracks().forEach(t=>t.stop());state='idle';$('timer').hidden=true;controls();feedback(s);}
function stop(){const s=session;if(!s||state!=='recording')return;state='stopping';controls();clearInterval(s.ticker);clearTimeout(s.limit);status('Checking what we heard…');if(s.recorder.state!=='inactive')s.recorder.stop();else s.audioDone=true;s.stream.getTracks().forEach(t=>t.stop());if(s.recognizing){try{s.recognition.stop();}catch{s.speechDone=true;}}else s.speechDone=true;s.fallback=setTimeout(()=>{s.speechDone=true;try{s.recognition.abort();}catch{}finish(s);},4000);finish(s);}
async function start(){state='starting';controls();cancelExample();$('audio').pause();$('feedback').hidden=true;$('playback').hidden=true;status('Allow microphone access to begin.');const s={transcript:'',chunks:[],recognizing:false,audioDone:false,speechDone:false,finished:false};session=s;try{s.stream=await navigator.mediaDevices.getUserMedia({audio:true});s.recorder=new MediaRecorder(s.stream);s.recognition=new Recognition();s.recognition.lang='es-MX';s.recognition.continuous=true;s.recognition.interimResults=false;
 s.recognition.onresult=e=>{if(s.finished)return;for(let i=e.resultIndex;i<e.results.length;i++)if(e.results[i].isFinal)s.transcript+=' '+e.results[i][0].transcript;};
 s.recognition.onerror=e=>{if(e.error==='no-speech'||e.error==='aborted')return;const errors={'not-allowed':'Speech recognition permission was denied. Allow microphone access in your browser settings and try again.','service-not-allowed':'Your browser’s speech service is unavailable. Try Chrome.','network':'The speech service could not connect. Check your internet connection and try again.','audio-capture':'The microphone is unavailable. Check its connection and try again.'};s.error=errors[e.error]||'Speech recognition failed. Please try again.';if(state==='recording')stop();};
 s.recognition.onend=()=>{s.recognizing=false;if(state==='recording'&&!s.error){try{s.recognition.start();s.recognizing=true;}catch{s.error='Speech recognition stopped. Please try recording again.';stop();}}else{s.speechDone=true;finish(s);}};
 s.recorder.ondataavailable=e=>{if(e.data.size)s.chunks.push(e.data);};
 s.recorder.onstop=()=>{s.audioDone=true;if(audioUrl)URL.revokeObjectURL(audioUrl);if(s.chunks.length){audioUrl=URL.createObjectURL(new Blob(s.chunks,{type:s.recorder.mimeType}));$('audio').src=audioUrl;$('playback').hidden=false;}finish(s);};
 s.recorder.onerror=()=>{s.error='Recording failed. Check your microphone and try again.';stop();};
 s.recognition.start();s.recognizing=true;s.recorder.start();state='recording';controls();status('Listening… Read the Spanish sentence, then tap Finish recording.');s.started=Date.now();$('timer').hidden=false;$('timer').textContent='0:00';s.ticker=setInterval(()=>{const sec=Math.floor((Date.now()-s.started)/1000);$('timer').textContent=`${Math.floor(sec/60)}:${String(sec%60).padStart(2,'0')}`;},250);s.limit=setTimeout(()=>{stop();},120000);
 }catch(error){s.finished=true;s.stream?.getTracks().forEach(t=>t.stop());try{s.recognition?.abort();}catch{}state='idle';controls();status(error.name==='NotAllowedError'?'Microphone access was denied. Allow it in your browser settings, then try again.':'Could not start recording. Check your microphone and use Chrome over HTTPS.');}}
$('record').addEventListener('click',()=>state==='recording'?stop():state==='idle'?start():undefined);
$('next').addEventListener('click',()=>{cancelExample();$('audio').pause();index=(index+1)%sentences.length;render();});
$('listen').addEventListener('click',()=>{$('audio').pause();speakExample(sentences[index][0],()=>status('The example audio is unavailable. You can still read the sentence and record.'));});
window.addEventListener('pagehide',()=>{if(session){clearInterval(session.ticker);clearTimeout(session.limit);clearTimeout(session.fallback);session.finished=true;session.recognition?.abort();session.stream?.getTracks().forEach(t=>t.stop());}cancelExample();});
render();if(!Recognition||!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)status('Recording is unavailable in this browser. Open this page in Chrome with microphone access enabled.');

document.getElementById('version').textContent = `v${version}`;
